name: Publish to NPM
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc
      - run: git config --global user.name "$GITHUB_SHA"
      - run: cat ~/.npmrc
      - run: env
      - run: npm whoami
      - run: npm run release