name: Publish to NPM
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: echo "_auth = $NPM_ACCESS_TOKEN" > ~/.npmrc
      - run: echo "email = $NPM_PUBLIC_EMAIL" >> ~/.npmrc
      - run: cat ~/.npmrc
      - run: npm whoami
      - run: npm run release