name: Publish to NPM
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: login to npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN }}" > ~/.npmrc
          git config --global user.name "rubybb"
          npm whoami
      - name: install dependencies
        run: |
          npm i
      - name: release package
        run: |
          npm version minor
          npm run release